name: Salesforce Automation Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SF_ALIAS: RealEstateDemoScratch
      DEV_HUB_ALIAS: DevHub

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --location=global
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      - name: Write server.key from secret
        run: echo "${{ secrets.SERVER_KEY }}" > server.key

      - name: Authenticate to Dev Hub (JWT)
        run: |
          sf org login jwt \
            --username ${{ secrets.SF_USERNAME }} \
            --jwt-key-file server.key \
            --client-id ${{ secrets.CLIENT_ID }} \
            --set-default-dev-hub \
            --alias $DEV_HUB_ALIAS

      - name: Delete ALL active scratch orgs (limit free-up)
        run: |
          sf org list --all --json > orgs.json
          # Delete all ACTIVE scratch orgs
          cat orgs.json | grep -o '"alias":"[^"]*","type":"Scratch","status":"Active"' | awk -F'"' '{print $4}' | while read alias; do
            sf org delete scratch --target-org "$alias" -p || true
          done

      - name: Create scratch org
        run: |
          sf org create scratch -f config/project-scratch-def.json -a $SF_ALIAS --duration-days 7 --set-default

      - name: Push metadata
        run: sf project deploy start

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate CSVs from Excel
        run: |
          . venv/bin/activate
          python scripts/generate_csv.py

      - name: Import Demo Data
        run: |
          . venv/bin/activate
          python scripts/import_data.py

      - name: Pipeline Results and Scratch Org URL
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Pipeline completed successfully!"
          else
            echo "❌ Pipeline failed — check logs for details."
          fi
          echo "🔗 Scratch Org URL:"
          sf org open --target-org $SF_ALIAS -r || echo "No active org to open."
          
    #   - name: Cleanup (Delete Scratch Org at End)
    #     if: always()
    #     run: |
    #       sf org delete scratch --target-org $SF_ALIAS -p || echo "Scratch org not found for cleanup."