name: Salesforce Data Import Pipeline

on:
  push:
    branches:
      - main

jobs:
  import_data:
    runs-on: ubuntu-latest

    env:
      MAIN_ORG_ALIAS: MainOrg

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Salesforce CLI (sf)
        run: |
          npm install @salesforce/cli --location=global
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      - name: Write server.key from secret
        run: echo "${{ secrets.SERVER_KEY }}" > server.key

      - name: Authenticate to Main Org (JWT)
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          sf org login jwt \
            --username "$SF_USERNAME" \
            --jwt-key-file server.key \
            --client-id "$CLIENT_ID" \
            --alias $MAIN_ORG_ALIAS \
            --set-default

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate CSVs from Excel
        run: |
          . venv/bin/activate
          python scripts/generate_csv.py

      - name: Import Accounts CSV
        run: |
          sfdx force:data:bulk:upsert -s Account -f Account.csv -i Id --targetusername $MAIN_ORG_ALIAS

      - name: Import Contacts CSV
        run: |
          sfdx force:data:bulk:upsert -s Contact -f Contact.csv -i Id --targetusername $MAIN_ORG_ALIAS

      - name: Import Opportunities CSV
        run: |
          sfdx force:data:bulk:upsert -s Opportunity -f Opportunity.csv -i Id --targetusername $MAIN_ORG_ALIAS

      - name: Pipeline Results
        if: always()
        run: |
          echo "✅ Pipeline completed successfully (CSV import)!"
