name: Salesforce Main Org Deployment Validation

on:
  push:
    branches:
      - main

jobs:
  validate_deploy:
    runs-on: ubuntu-latest

    env:
      MAIN_ORG_ALIAS: MainOrg

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --location=global
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH

      - name: Write server.key from secret
        run: echo "${{ secrets.SERVER_KEY }}" > server.key

      - name: Authenticate to Main Org (JWT)
        env:
            SF_USERNAME: ${{ secrets.SF_USERNAME }}
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
            sf org login jwt \
            --username "$SF_USERNAME" \
            --jwt-key-file server.key \
            --client-id "$CLIENT_ID" \
            --alias MainOrg \
            --set-default-org            

    #   - name: Validate Metadata deployment (checkonly)
    #     run: |
    #       sf project deploy start --target-org $MAIN_ORG_ALIAS --checkonly

      - name: Setup Python environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate CSVs from Excel (Validation run)
        run: |
          . venv/bin/activate
          python scripts/generate_csv.py

      - name: Import Demo Data (Validation run)
        run: |
          . venv/bin/activate
          python scripts/import_data.py

      - name: Pipeline Results
        if: always()
        run: |
          echo "✅ Pipeline completed successfully!"
          echo "⚠️ Note: This was validation only, no changes have been applied to main org."
